/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package suppliers;

import transaction.*;
import gardeniastoremanagementsystem.BuiltSystem;
import gardeniastoremanagementsystem.GardeniaStoreManagementSystem;
import members.*;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Xxark
 */
public class SupplierShowPage extends javax.swing.JFrame {

    /**
     * Creates new form MemberDeleteConfirmation
     */
    int trans_id;
    int total_recap;
    
    Connection connection;
    public SupplierShowPage() {
        connection = BuiltSystem.CreateConnection(connection);
        initComponents();
        this.setVisible(true);
        this.setLocation(300,120);
        this.setSize(900,320);
        this.setResizable(false);

        
        JTableHeader header = tableDetail.getTableHeader();
        header.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Font verdanaFont = new Font("Verdana", Font.PLAIN, 14); // Font, style, size
        header.setFont(verdanaFont);
        header.setBackground(new Color(34, 23, 122));
        header.setForeground(Color.WHITE);   

        
        

        
        RefreshData();
        
//        totalMember.setText("Total Transaction : " + transactions.ids_trans.size());
    }
    
    public void RefreshData() {
        BuiltSystem.debugLog("Running RefreshData()");
        
        DefaultTableModel tableModel = (DefaultTableModel)tableDetail.getModel();
        Suppliers suppliers = new Suppliers();
        String supplier_id, supplier_name, supplier_phone;
        int size = suppliers.supplier_ids.size();
        int total_row = tableModel.getRowCount();
        for (int i = 0; i < total_row; i++) tableModel.removeRow(0);
        for (int i = 0; i < size;  i++) {

            supplier_id = suppliers.supplier_ids.get(i);
            supplier_name = suppliers.supplier_names.get(i);
            supplier_phone = suppliers.supplier_phones.get(i);
            String rowData[] = {supplier_id, supplier_name, supplier_phone};
            
            tableModel.addRow(rowData);
//            BuiltSystem.debugLog("selected id product : "+ id_products);
            
            
        }   
//        BuiltSystem.debugLog("Product "+ trans.Dids_products.get(i) + " deleted from productID");
    
        BuiltSystem.debugLog("RefreshData() Completed");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        detailClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetail = new javax.swing.JTable();
        InsertSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 282));

        detailClose.setBackground(new java.awt.Color(96, 94, 161));
        detailClose.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        detailClose.setForeground(new java.awt.Color(255, 255, 255));
        detailClose.setText("close");
        detailClose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        detailClose.setFocusCycleRoot(true);
        detailClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                detailCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                detailCloseMouseExited(evt);
            }
        });
        detailClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailCloseActionPerformed(evt);
            }
        });

        tableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Supplier_id", "Name", "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDetail);
        if (tableDetail.getColumnModel().getColumnCount() > 0) {
            tableDetail.getColumnModel().getColumn(0).setResizable(false);
            tableDetail.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableDetail.getColumnModel().getColumn(1).setResizable(false);
            tableDetail.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableDetail.getColumnModel().getColumn(2).setResizable(false);
            tableDetail.getColumnModel().getColumn(2).setPreferredWidth(250);
        }

        InsertSupplier.setBackground(new java.awt.Color(96, 94, 161));
        InsertSupplier.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        InsertSupplier.setForeground(new java.awt.Color(255, 255, 255));
        InsertSupplier.setText("New");
        InsertSupplier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        InsertSupplier.setFocusCycleRoot(true);
        InsertSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InsertSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InsertSupplierMouseExited(evt);
            }
        });
        InsertSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(InsertSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detailClose, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsertSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailCloseMouseExited
        detailClose.setBackground(new Color(96, 94, 161));
    }//GEN-LAST:event_detailCloseMouseExited

    private void detailCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailCloseMouseEntered
        detailClose.setBackground(new Color(204, 43, 82));
    }//GEN-LAST:event_detailCloseMouseEntered

    private void detailCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_detailCloseMouseClicked

    private void detailCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailCloseActionPerformed

    private void InsertSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertSupplierMouseClicked
        // TODO add your handling code here:
        new SupplierRegistration();
    }//GEN-LAST:event_InsertSupplierMouseClicked

    private void InsertSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertSupplierMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertSupplierMouseEntered

    private void InsertSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertSupplierMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertSupplierMouseExited

    private void InsertSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertSupplierActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertSupplier;
    private javax.swing.JButton detailClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDetail;
    // End of variables declaration//GEN-END:variables


}
